services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_standalone
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data:/data/db

  mongo-client:
    image: mongo:latest
    container_name: mongo_client
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - mongodb

volumes:
  mongo-data:
